### PR TITLE
Adding tabs to leaderboard

### PR DESCRIPTION
**Pull request by ChangoMan**
Adding tabs to the leaderboard. Ended up using shadcn tabs because the Daisy UI tabs were not working well on mobile

Screenshot 2024-11-10 at 4 41 30 PM

### CODE REVIEW

**Review by damianmarti — APPROVED** [review]
Sad DaisyUI tabs do not work well on mobile :-(

Thanks!!

**Comment by damianmarti** [comment]
@ChangoMan can you please fix the merge conflicts?

**Comment by ChangoMan** [comment]
@damianmarti Fixed!

**Comment by damianmarti** [comment]
> @damianmarti Fixed!

Thanks!!!

**Pull request merged**
